### ISSUE TITLE
README needs more info on: Best Practice + Is there a reason that required_valid_user's default value is false?

### ISSUE THREAD

**Issue by desmap** [apache/couchdb-docker#138]
I'd like to understand the thoughts behind why `required_valid_user` is set to `false` as the default of this Docker image and not `true`?

Is it not best practice (in the context of this Docker image) to have:
1. A secure DB with `required_valid_user = true`  in `[chttpd]` and in `[couch_httpd_auth]`
2. All CouchDB ports firewalled/not open to the outside
3. To make DB requests from the app server via the 'server admin' user, just in order to save extra steps when setting up everything (again all in the context of using this Docker image and expecting a turn-key UX)

Only if the actual application use case requires more users with granular rights per db, then more users in `_users` should be created. But then still bullet 1 should be followed and set to `true`, I guess?! 

I mean only if I build something like npm then I need to have `required_valid_user = false` for the packages db but I'd assume that such use cases are rather rare. Maybe I missed something but a clarification in the README would be super helpful why defaults x and y are chosen.

**Comment by wohali** [comment]
It is the policy of this image to follow the defaults of CouchDB.

The CouchDB default policy is `require_valid_user = false`. This was a deliberate decision in CouchDB 1.x, at the dawn of the NoSQL movement, to encourage data sharing.

To ensure maximal backward compatibility, that policy will not change until CouchDB 3.x; if you are interested in following along with that change, see https://github.com/apache/couchdb/issues/1504 .

Another limiting factor is that because it is not clear if the Docker image is being used to create a single node or a cluster, `_users` cannot be created prior to joining the nodes together in a cluster, or the database will be unbalanced in production use. This is a problem that must be resolved going forward as well, and not within the context of the Docker container.

**Comment by desmap** [comment]
@wohali, thanks for your quick reply , this was very helpful and now I get it. I still would suggest to put a note in the README. 

Moreover, I'd propose to expose `required_valid_user` via an env var, I'll elaborate more on this in a new issue.
