### ISSUE TITLE
Expose required_valid_user via env var

### ISSUE THREAD

**Issue by desmap** [apache/couchdb-docker#139]
Since securing a DB is important and `required_valid_user` is set to false as default in this Docker image, I propose to have an env var to change this within the `docker-compose.yml`. A nice side effect would be that we signal the importance of `required_valid_user` and the DB security in general.

Just to give you an illustration, what needs to be done w/o an env var. E.g. in node, I have to put following boilerplate in front of my app in order to have the automatic setting of `required_valid_user` without fiddling with config files.. 
Btw, I cannot use regular nano functions because `required_valid_user` is not exposed there. So, I end up with custom requests...
```
const dbUrl = `http://${process.env.COUCHDB_USER}:${process.env.COUCHDB_PASSWORD}@db:5984`
const nano = require('nano')(dbUrl)
request
  .put(`${dbUrl}/_node/nonode@nohost/_config/chttpd/require_valid_user`)
  .send('"true"')
  .catch(err => {
    console.log(err.message, err.response)
  })
request
  .put(`${dbUrl}/_node/nonode@nohost/_config/couch_httpd_auth/require_valid_user`)
  .send('"true"')
  .catch(err => {
    console.log(err.message, err.response)
  })
```

**Comment by wohali** [comment]
You should simply create a new `10-require-valid-user.ini` file and place it into the /opt/couchdb/etc/local.d directory as documented. You can mount this directory externally when launching the container.

This new setting will take effect immediately on launch as you want.

**Comment by wohali** [comment]
For others driving by, see #137 for more information.

**Comment by desmap** [comment]
@wohali, thx for your fast response.

> You should simply create a new 10-require-valid-user.ini file and place it

This is even easier and a good idea but still more work than setting a simple env var. 

And we would miss the opportunity to stress that this is an important setting. Now, you create the notion with exposing only the env vars `COUCHDB_USER` and `COUCHDB_PASSWORD` that all is good after setting those. I know, once people read the docs, things get clear but still.

> For others driving by, see #137 for more information.

Would you mind to elaborate what is the relation between than issue and this issue?

**Comment by wohali** [comment]
@desmap if you hadn't run into #137  you wouldn't be asking for this in #138.

We made a decision to stop support additional environment variables a while ago because there were endless requests to just "special case" another env var, and it became a large burden.

I disagree with you that this is a critical change. We have thousands of people deploying CouchDB today in cluster form who absolutely could not use the changes you propose, and a k8s helm chart that does the heavy work of setting up a cluster with proper security as well.

Doing something like `require_valid_user = true` also causes problems for things like health check scripts at load balancers ahead of a CouchDB cluster since they cannot `GET /` or `GET /_up` without credentials. Many automated / SaaS systems do not have the ability to provide credentials for health check purposes. It is a sub-par approach.

The 100% best approach to date is to never bind CouchDB to anything other than a locally accessible network. Normally, that's 127.0.0.1, but with Docker that can be your Docker networking that you should not be exposing outside of your application server enviornment. After setting up an admin user (with USER/PASSWORD) CouchDB isn't wide open, and with a `_security` object on your databases, it's even more locked down. These are all normal parts of configuring CouchDB today, and I do not wish to make the Docker container seem like it's doing something different just because it feels like it.

The _right_ fix for this is the 3.x rework of CouchDB security, which is a high priority for the development team.

**Comment by desmap** [comment]
Dear @wohali, thanks for the explanation and it makes sense what you have written. I did not intend to bind CouchDB to anything else than 127.0.0.1, so I could just leave `required_valid_user` on false but I guess, it's just having a bad gut feeling and better safe than sorry. 

However, also thanks for your responsiveness and general good feedback today. And apologies for creating all that issues, I am just super excited about CouchDB and testing things in and out (was my first day with CouchDB).

**Comment by wohali** [comment]
Which we do with the admin user, which ends admin party.

Ensuring per-database security settings are correct is up to you.

**Comment by desmap** [comment]
> Which we do with the admin user, which ends admin party.

This is a bit misleading + comparing apples'n'oranges. Postgres', MySQL's, Mongo's Docker images can all be **fully** locked-down using only env vars while CouchDB's Docker image **cannot** be fully locked-down using env vars only => check your post above where you rail against a full lock-down *(Doing [...] causes problems)* and pls check also https://github.com/apache/couchdb-docker/issues/37#issuecomment-339698316 

Would be great if we are not discussing now if a full lock-down via env vars is useful or not ;), all major db images expose this feature and you closed this issue anyway. Let's just agree to disagree and all good, I still appreciate our conversation. But put rather your energy in improving the README and explaining all these (not obvious) design decisions, this would help users more since CouchDB is actually a great product, for others driving by => https://github.com/apache/couchdb-docker/issues/138

**Comment by wohali** [comment]
We're not changing anything with the Docker image approach until the base product reworks how CouchDB security works. Docker isn't magic and your approach doesn't make any sense for cluster installations, which is a large percentage of CouchDB installations.

Locking this thread.
