### ISSUE TITLE
Table _users does not exist even its declared in variables

### ISSUE THREAD

**Issue by pbajno** [apache/couchdb-docker#198]
![image](https://user-images.githubusercontent.com/18303501/109554018-645ad400-7adc-11eb-8a97-85064fdf04da.png)

[notice] 2021-03-01T20:20:36.696613Z couchdb@couchdb0 <0.329.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.

I also pass this variables unto docker
```
      COUCHDB_SECRET: secret
      COUCHDB_USER: user
      COUCHDB_PASSWORD: password
      NODENAME: couchdb
```

Still no effect. I got same from using your build and mine from cloning 3.1.1 folder with Dockerfile.

**Comment by wohali** [comment]
This is intentional. We cannot know at startup if the node will be a standalone, single node, or in a cluster. If it's clustered, creating the database is **provably wrong** and will break everything.

If you know you are setting up a single node instance, you can create the `_users` and `_replicator` databases after startup to remove these errors.
