### ISSUE TITLE
Build docker image on push to master

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb-docker#4]
From docker-couchdb: klaemo/docker-couchdb#106  

HOw does the couchdb 2.0-dev tag get updated? Ideally it would be great if it was rebuilt on every push to couchdb master. That way we can stay nice and current.

**Comment by garrensmith** [comment]
From @klaemo 

that would require a proper Dockerfile in the couchdb repo. Ages go I tried to implement that (apache/couchdb#340), but it went nowhere.

Currently 2.0-dev points to 2.0-rc1 which is rather odd (https://github.com/klaemo/docker-couchdb/blob/master/2.0-dev/Dockerfile#L59). It could point to commit hashes as well. On every push to this repo, docker hub rebuilds the images.

**Comment by garrensmith** [comment]
Moved to https://github.com/apache/couchdb-docker/issues/5

**Comment by wohali** [comment]
We've been told we cannot do this anymore, per ASF policy: 

Please see: http://www.apache.org/dev/release-distribution.html#unreleased

The middle two bullet points are the issue here. We cannot violate this policy and endanger our status as an ASF official project.

As such this will not be happening, sorry. Only official releases will be published to Docker Hub. As compensation, we are working to step up our release cadence to every 3-6 months.
